<?php

declare(strict_types=1);

/**
 * Copyright (c) 2022-2022 Flexic-Systems
 *
 * @author Hendrik Legge <hendrik.legge@themepoint.de>
 *
 * @version 1.0.0
 */

namespace Flexic\DataProvider\Payment;

use Flexic\DataProvider\AbstractProvider;

final class CurrencyCodeProvider extends AbstractProvider
{
    /**
     * @return \Generator<string, array{0: string}>
     */
    public static function arbitrary(): \Generator
    {
        yield from self::provideDataForValues(self::values());
    }

    public static function values(): array
    {
        $faker = self::faker();

        return [
            'currency-code' => $faker->randomElement([
                'AFA',
                'ALL',
                'DZD',
                'AOA',
                'ARS',
                'AMD',
                'AWG',
                'AUD',
                'AZN',
                'BSD',
                'BHD',
                'BDT',
                'BBD',
                'BYR',
                'BEF',
                'BZD',
                'BMD',
                'BTN',
                'BTC',
                'BOB',
                'BAM',
                'BWP',
                'BRL',
                'GBP',
                'BND',
                'BGN',
                'BIF',
                'KHR',
                'CAD',
                'CVE',
                'KYD',
                'XOF',
                'XAF',
                'XPF',
                'CLP',
                'CNY',
                'COP',
                'KMF',
                'CDF',
                'CRC',
                'HRK',
                'CUC',
                'CZK',
                'DKK',
                'DJF',
                'DOP',
                'XCD',
                'EGP',
                'ERN',
                'EEK',
                'ETB',
                'EUR',
                'FKP',
                'FJD',
                'GMD',
                'GEL',
                'DEM',
                'GHS',
                'GIP',
                'GRD',
                'GTQ',
                'GNF',
                'GYD',
                'HTG',
                'HNL',
                'HKD',
                'HUF',
                'ISK',
                'INR',
                'IDR',
                'IRR',
                'IQD',
                'ILS',
                'ITL',
                'JMD',
                'JPY',
                'JOD',
                'KZT',
                'KES',
                'KWD',
                'KGS',
                'LAK',
                'LVL',
                'LBP',
                'LSL',
                'LRD',
                'LYD',
                'LTL',
                'MOP',
                'MKD',
                'MGA',
                'MWK',
                'MYR',
                'MVR',
                'MRO',
                'MUR',
                'MXN',
                'MDL',
                'MNT',
                'MAD',
                'MZM',
                'MMK',
                'NAD',
                'NPR',
                'ANG',
                'TWD',
                'NZD',
                'NIO',
                'NGN',
                'KPW',
                'NOK',
                'OMR',
                'PKR',
                'PAB',
                'PGK',
                'PYG',
                'PEN',
                'PHP',
                'PLN',
                'QAR',
                'RON',
                'RUB',
                'RWF',
                'SVC',
                'WST',
                'SAR',
                'RSD',
                'SCR',
                'SLL',
                'SGD',
                'SKK',
                'SBD',
                'SOS',
                'ZAR',
                'KRW',
                'XDR',
                'LKR',
                'SHP',
                'SDG',
                'SRD',
                'SZL',
                'SEK',
                'CHF',
                'SYP',
                'STD',
                'TJS',
                'TZS',
                'THB',
                'TOP',
                'TTD',
                'TND',
                'TRY',
                'TMT',
                'UGX',
                'UAH',
                'AED',
                'UYU',
                'USD',
                'UZS',
                'VUV',
                'VEF',
                'VND',
                'YER',
                'ZMK',
            ]),
        ];
    }
}
