<?php

declare(strict_types=1);

/**
 * Copyright (c) 2022-2022 Flexic-Systems
 *
 * @author Hendrik Legge <hendrik.legge@themepoint.de>
 *
 * @version 1.0.0
 */

namespace Flexic\DataProvider\Payment;

use Flexic\DataProvider\AbstractProvider;

final class CurrencyProvider extends AbstractProvider
{
    /**
     * @return \Generator<string, array{0: string}>
     */
    public static function arbitrary(): \Generator
    {
        yield from self::provideDataForValues(self::values());
    }

    public static function values(): array
    {
        $faker = self::faker();

        return [
            'currencies' => $faker->randomElement([
                'Afghan Afghani',
                'Albanian Lek',
                'Algerian Dinar',
                'Angolan Kwanza',
                'Argentine Peso',
                'Armenian Dram',
                'Aruban Florin',
                'Australian Dollar',
                'Azerbaijani Manat',
                'Bahamian Dollar',
                'Bahraini Dinar',
                'Bangladeshi Taka',
                'Barbadian Dollar',
                'Belarusian Ruble',
                'Belgian Franc',
                'Belize Dollar',
                'Bermudan Dollar',
                'Bhutanese Ngultrum',
                'Bitcoin',
                'Bolivian Boliviano',
                'Bosnia',
                'Botswanan Pula',
                'Brazilian Real',
                'British Pound Sterling',
                'Brunei Dollar',
                'Bulgarian Lev',
                'Burundian Franc',
                'Cambodian Riel',
                'Canadian Dollar',
                'Cape Verdean Escudo',
                'Cayman Islands Dollar',
                'CFA Franc BCEAO',
                'CFA Franc BEAC',
                'CFP Franc',
                'Chilean Peso',
                'Chinese Yuan',
                'Colombian Peso',
                'Comorian Franc',
                'Congolese Franc',
                'Costa Rican ColÃ³n',
                'Croatian Kuna',
                'Cuban Convertible Peso',
                'Czech Republic Koruna',
                'Danish Krone',
                'Djiboutian Franc',
                'Dominican Peso',
                'East Caribbean Dollar',
                'Egyptian Pound',
                'Eritrean Nakfa',
                'Estonian Kroon',
                'Ethiopian Birr',
                'Euro',
                'Falkland Islands Pound',
                'Fijian Dollar',
                'Gambian Dalasi',
                'Georgian Lari',
                'German Mark',
                'Ghanaian Cedi',
                'Gibraltar Pound',
                'Greek Drachma',
                'Guatemalan Quetzal',
                'Guinean Franc',
                'Guyanaese Dollar',
                'Haitian Gourde',
                'Honduran Lempira',
                'Hong Kong Dollar',
                'Hungarian Forint',
                'Icelandic KrÃ³na',
                'Indian Rupee',
                'Indonesian Rupiah',
                'Iranian Rial',
                'Iraqi Dinar',
                'Israeli New Sheqel',
                'Italian Lira',
                'Jamaican Dollar',
                'Japanese Yen',
                'Jordanian Dinar',
                'Kazakhstani Tenge',
                'Kenyan Shilling',
                'Kuwaiti Dinar',
                'Kyrgystani Som',
                'Laotian Kip',
                'Latvian Lats',
                'Lebanese Pound',
                'Lesotho Loti',
                'Liberian Dollar',
                'Libyan Dinar',
                'Lithuanian Litas',
                'Macanese Pataca',
                'Macedonian Denar',
                'Malagasy Ariary',
                'Malawian Kwacha',
                'Malaysian Ringgit',
                'Maldivian Rufiyaa',
                'Mauritanian Ouguiya',
                'Mauritian Rupee',
                'Mexican Peso',
                'Moldovan Leu',
                'Mongolian Tugrik',
                'Moroccan Dirham',
                'Mozambican Metical',
                'Myanmar Kyat',
                'Namibian Dollar',
                'Nepalese Rupee',
                'Netherlands Antillean Guilder',
                'New Taiwan Dollar',
                'New Zealand Dollar',
                'Nicaraguan CÃ³rdoba',
                'Nigerian Naira',
                'North Korean Won',
                'Norwegian Krone',
                'Omani Rial',
                'Pakistani Rupee',
                'Panamanian Balboa',
                'Papua New Guinean Kina',
                'Paraguayan Guarani',
                'Peruvian Nuevo Sol',
                'Philippine Peso',
                'Polish Zloty',
                'Qatari Rial',
                'Romanian Leu',
                'Russian Ruble',
                'Rwandan Franc',
                'Salvadoran ColÃ³n',
                'Samoan Tala',
                'Saudi Riyal',
                'Serbian Dinar',
                'Seychellois Rupee',
                'Sierra Leonean Leone',
                'Singapore Dollar',
                'Slovak Koruna',
                'Solomon Islands Dollar',
                'Somali Shilling',
                'South African Rand',
                'South Korean Won',
                'Special Drawing Rights',
                'Sri Lankan Rupee',
                'St. Helena Pound',
                'Sudanese Pound',
                'Surinamese Dollar',
                'Swazi Lilangeni',
                'Swedish Krona',
                'Swiss Franc',
                'Syrian Pound',
                'São Tomé and Príncipe Dobra',
                'Tajikistani Somoni',
                'Tanzanian Shilling',
                'Thai Baht',
                "Tongan pa'anga",
                'Trinidad & Tobago Dollar',
                'Tunisian Dinar',
                'Turkish Lira',
                'Turkmenistani Manat',
                'Ugandan Shilling',
                'Ukrainian Hryvnia',
                'United Arab Emirates Dirham',
                'Uruguayan Peso',
                'US Dollar',
                'Uzbekistan Som',
                'Vanuatu Vatu',
                'Venezuelan BolÃvar',
                'Vietnamese Dong',
                'Yemeni Rial',
                'Zambian Kwacha',
            ]),
        ];
    }
}
